import React, {Component} from 'react';
import { connect } from 'react-redux';
import { selectBook } from '../action/index'; // From index.js in actions to selectBook
import { bindActionCreators } from 'redux'; // Function in redux used to make sure
// that the action generated by the action creator actually flows through all the reducers

class BookList extends Component {
  renderList() {
    return this.props.books.map((book) => {
      return (
        <li key={book.title} className="list-group-item">{book.title}</li>
      );
    });
  }

  render() {
    return (
      <div className="list-group col-sm-6">
        {this.renderList()}
      </div>
    )
  }
}

function mapStateToProps(state) {
  // Whatever is returned will show up as props inside of BookList
  return {
    books: state.books
  };
}
// Anything returned from this function will end up as props
// on the BookList container
function mapDispatchToProps(dispatch) {
  // Whenever selectBook is called, the result should be passed to all of our reducers
  return bindActionCreators({ selectBook: selectBook }, dispatch);
}

// Promote BookList from a component to a container - it needs to know about
// this new dispatch method, selectBook.  Make it available as a prop
export default connect(mapStateToProps, mapDispatchToProps)(BookList);